services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mirlo
      POSTGRES_PASSWORD: mirlo
      POSTGRES_DB: mirlo
    volumes:
      - .postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
